name: Integration Tests
on: push
jobs:
  go-tests:
    name: Run Integration Tests (terratest)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-go@v1
        with:
          go-version: 1.17
      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.2
          terraform_wrapper: false
      - name: Download Go modules
        working-directory: tests
        run: go mod download
      - name: Run tests
        working-directory: tests
        run: make integration-test
        env:
          ARM_SUBSCRIPTION_ID: ${{ secrets.SUBSCRIPTION_ID }}
          AZURE_SUBSCRIPTION_ID: ${{ secrets.SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.TENANT_ID }}
          AZURE_TENANT_ID: ${{ secrets.TENANT_ID }}
          ARM_CLIENT_ID: ${{ secrets.CLIENT_ID }}
          AZURE_CLIENT_ID: ${{ secrets.CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          AZURE_CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
